### ISSUE TITLE
Unable to view messages of a topic

### ISSUE THREAD

**Issue by aruldd** [obsidiandynamics/kafdrop#118]
Configuration:

Docker Compose
```
kafdrop:
    image: obsidiandynamics/kafdrop
    environment:
      - SERVER_SERVLET_CONTEXTPATH=/
      - JVM_OPTS=-Xms32M -Xmx64M
      - KAFKA_BROKERCONNECT=kafka:9092
    ports:
      - "${PORT_KAFDROP}:9000"
```
Image Digest: 93d80e41f51101833df3e91f0140bf27b533a7240faec112f1017927947d7a6e

Getting the following error while clicking on the view messages button
![image](https://user-images.githubusercontent.com/8513443/80689697-54a0e680-8aeb-11ea-959b-ff5dcda688b4.png)
![image](https://user-images.githubusercontent.com/8513443/80689712-59fe3100-8aeb-11ea-90b5-0eff9ec022bc.png)
