### ISSUE TITLE
[Question] Cannot connect to Kafka using Docker, but in local

### ISSUE THREAD

**Issue by WilliamWsyHK** [obsidiandynamics/kafdrop#125]
Hi,

I tried to connect to Kafka using both local and docker way, and found that only local jar file is able to find the Kafka. I would like to know if there is anything missing.

```sh
# local way
java --add-opens=java.base/sun.nio.ch=ALL_UNNAMED -jar kafdrop-3.26.0.jar --kafka.brokerConnect=localhost:9092
```

```yml
# docker-compose.yml
version: '3'
services:
  zookeeper:
    build: ./zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./kafka
    container_name: kafka
    ports:
      - "9092:9092"
    restart: "no"
    environment:
      # KAFKA_LISTENERS_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      # KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      # KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://:9092"
      # KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
  kafdrop:
    image: obsidiandynamics/kafdrop
    # build: ./kafdrop
    container_name: kafdrop
    ports:
      - "9001:9000"
    restart: "no"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092" # <-- not working, seeing the log giving localhost:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
      CMD_ARGS: "--kafka.brokerConnect=kafka:9092" # <-- also not working
      # CMD_ARGS: "--message.format=PROTOBUF --protobufdesc.directory=/var/protobuf_desc"
    depends_on:
      - "kafka"
```

Thanks in advance.
