### ISSUE TITLE
Dose kafdrop support more kafka-cluster?

### ISSUE THREAD

**Issue by istonehandsome** [obsidiandynamics/kafdrop#137]
under is my config. u can see that there are 2 kafka-cluster

first one is a standalone kafka,and another is 3 nodes kafka-cluster

```yaml
version: '2'
services:
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: 192.168.1.241:9092,192.168.3.115:32768,192.168.3.115:32769,192.168.3.115:32770
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
      CMD_ARGS: "--message.format=PROTOBUF --protobufdesc.directory=/var/protobuf_desc"
    volumes:
      - $PWD/protobuf_desc:/var/protobuf_desc

```

i find in [README.md](https://github.com/obsidiandynamics/kafdrop/blob/master/README.md) that it seems like support more kafka-cluster like this <b>BROKERCONNECT=<host:port,host:port> </b>
```sh
docker run -d --rm -p 9000:9000 \
    -e KAFKA_BROKERCONNECT=<host:port,host:port> \
    -e JVM_OPTS="-Xms32M -Xmx64M" \
    -e SERVER_SERVLET_CONTEXTPATH="/" \
    obsidiandynamics/kafdrop
```
otherwise i am wrong ,it means that there are some nodes host and port on a same kafka-cluster?
like my config  <b>192.168.3.115:32768,192.168.3.115:32769,192.168.3.115:32770</b>
