### ISSUE TITLE
Issue with connecting to a broker

### ISSUE THREAD

**Issue by Kamil-Zakiev** [obsidiandynamics/kafdrop#203]
Hi!
I'm trying to connect to kafka broker run on top of bitnami image and get errors:

```
2020-10-26 14:56:32.028 WARN 1 [| kafdrop-admin] o.a.k.c.NetworkClient : [AdminClient clientId=kafdrop-admin] Connection to node 1001 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
```

Providing docker-compose file below:
```
version: '2'

networks:
  kafka-net:
    driver: bridge

services:
  zoo:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
       - ALLOW_ANONYMOUS_LOGIN=yes
  broker1:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net    
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_EXTERNAL:PLAINTEXT,LISTENER_DOCKER_INTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=LISTENER_DOCKER_INTERNAL://:29092,LISTENER_DOCKER_EXTERNAL://:9092      
      - KAFKA_CFG_ADVERTISED_LISTENERS= LISTENER_DOCKER_INTERNAL://broker1:29092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME= LISTENER_DOCKER_INTERNAL
    depends_on:
      - zoo
  viewer:
    image: 'obsidiandynamics/kafdrop'
    networks:
      - kafka-net  
    ports:
      - '9000:9000'
    environment:
      - KAFKA_BROKERCONNECT=broker1:9092
      - JVM_OPTS=-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify
    depends_on:
      - broker1
```

Please clarify what I did wrong or missed
