### ISSUE TITLE
Setting SCHEMAREGISTRY_CONNECT from docker-compose.yml doesn't work

### ISSUE THREAD

**Issue by kaminzo** [obsidiandynamics/kafdrop#220]
Hi,
Tying to set SCHEMAREGISTRY_CONNECT as per below:

```
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "broker:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
      SCHEMAREGISTRY_CONNECT: "schema-registry:8081"
    depends_on:
      - broker
```
When opening up Kafdrop and trying to view messages with "Message format" set to Avro I am getting
`io.confluent.common.config.ConfigException: Invalid value null for configuration schema.registry.url: Expected a comma separated list`
