### ISSUE TITLE
kafdrop not working with ingress subpath

### ISSUE THREAD

**Issue by pankti11** [obsidiandynamics/kafdrop#261]
This does not seem to work. kafdrop works behind the proxy only with root url not with the subpath.

ingress configuration:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kafdrop-ui
  namespace: ix
  annotations:
   ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
        - backend:
            serviceName: kafdropui
            servicePort: 80
          path: /kafdrop/
```

![image](https://user-images.githubusercontent.com/25067151/113508604-a4dfbe80-956e-11eb-935e-c5fbd7fc9daa.png)

Any help with the configuration will be a great help. Thanks you !
