### ISSUE TITLE
Connection refused - No way to configure Zookeeper

### ISSUE THREAD

**Issue by Fosol** [obsidiandynamics/kafdrop#309]
I've attempted to use the docker container provided within my docker-compose setup.  However, it continues to attempt to make a socket connection to `localhost/127.0.0.1:2181`.  There appears no way to configure the network connection to Zookeeper.

My zookeeper is configured on a different network and on a different port within the docker-compose.

How do you configure kafdrop to correctly use the right network and port?

**Comment by davideicardi** [comment]
I'm using the following Docker Compose configuration:

```
version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
      
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_MESSAGE_MAX_BYTES: '10485760' # 10 MB
      KAFKA_REPLICA_FETCH_MAX_BYTES: '10485760' # 10 MB
      KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES: '10485760' # 10 MB
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 1G
        limits:
          memory: 2G

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
     - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9093
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    depends_on:
      - kafka
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
```

Let me know if you see problem with that.
