### ISSUE TITLE
Connection to node 1010 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.

### ISSUE THREAD

**Issue by mipo256** [obsidiandynamics/kafdrop#353]
I have k8s cluster with Kafka and kafdrop in it. Kafka is exposed by the means of headless service. Domain of kafka service within kubernetes cluster is `kafka-headless-service-dev`, kafka broker port is : _9092_.

Inside kafdrop pod I am able to resolve kafka service domain name into appropriate lan ip, see below:

![image](https://user-images.githubusercontent.com/68962645/153759654-f46988f7-46c7-4076-8cd7-9aff6422ada5.png)

I have created kafdrop deployment in k8s, the manifest is the folowwing:

```
apiVersion: v1
kind: Service
metadata:
  name: kafdrop-dev-nodeport
  namespace: dev
  labels:
    app.kubernetes.io/environment: dev
spec:
  type: NodePort
  selector:
    app.kubernetes.io/app-name: kafdrop
    app.kubernetes.io/environment: dev
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 32001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop-monitoring-service
  namespace: dev
  labels:
    app.kubernetes.io/type: monitoring
    app.kubernetes.io/app-name: kafdrop
    app.kubernetes.io/environment: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/app-name: kafdrop
      app.kubernetes.io/environment: dev
  template:
    metadata:
      labels:
        app.kubernetes.io/app-name: kafdrop
        app.kubernetes.io/environment: dev
    spec:
      containers:
      - name: kafdrop
        image: obsidiandynamics/kafdrop:3.28.0
        env:
          - name: KAFKA_BROKERCONNECT
            value: kafka-headless-service-dev:9092
          - name: SERVER_SERVLET_CONTEXTPATH
            value: '/'
        resources:
          requests:
            cpu: 250m
            memory: 350Mi
          limits:
            cpu: 300m
            memory: 400Mi
```

As you can see, there is an `KAFKA_BROKERCONNECT` env variable to be set inside kafdrop container within pod. And it does:

![image](https://user-images.githubusercontent.com/68962645/153759772-5aaa9101-5cec-416c-8c28-365165a5bbe8.png)

The problem seems to that for some reason kafdrop tries to connect to kafka broker inside its pod, i.e. by localhost:

`2022-02-13 15:14:21.603  WARN 1 [| kafdrop-admin] o.a.k.c.NetworkClient                    : [AdminClient clientId=kafdrop-admin] Connection to node 1010 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.`
 
And there is a lot of this messages in the logs. In accordance [to official docker image doc](https://hub.docker.com/r/obsidiandynamics/kafdrop)  KAFKA_BROKERCONNECT indicates the location of kafka broker to fetch info from, I have set it, but it does not seem to work - why?
