### ISSUE TITLE
Configuration needed to connect to secured cluster

### ISSUE THREAD

**Issue by ADefossez-Zenika** [obsidiandynamics/kafdrop#36]
Hi all, 

I want to connect to a kafka cluster hosted by aiven.io, i have a trustore-file, a keystore-file, and their respectives passwords.

I made a little docker-compose and provide env variables with the BASE64 encoded files.

```
version: "3"

services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment: 
      KAFKA_BROKERCONNECT: "mybroker..aivencloud.com:24117"
      KAFKA_PROPERTIES: "c3Nblablablrcw=="
      KAFKA_TRUSTSTORE: "/u3blablabla=="
      KAFKA_KEYSTORE: "/u3+7blablabladyLfz/y"
```

I have a message in my logs; 
```
kafdrop_1  | 2019-10-10 12:24:25.663  WARN 13 [           main] o.a.k.c.c.AbstractConfig                 : The configuration 'ssl.truststore.location' was supplied but isn't a known config.
kafdrop_1  | 2019-10-10 12:24:25.663  WARN 13 [           main] o.a.k.c.c.AbstractConfig                 : The configuration 'ssl.keystore.password' was supplied but isn't a known config.
kafdrop_1  | 2019-10-10 12:24:25.664  WARN 13 [           main] o.a.k.c.c.AbstractConfig                 : The configuration 'ssl.keystore.location' was supplied but isn't a known config.
kafdrop_1  | 2019-10-10 12:24:25.664  WARN 13 [           main] o.a.k.c.c.AbstractConfig                 : The configuration 'ssl.truststore.password' was supplied but isn't a known config.

```

Note : my kafka.properties is very simple 

```
ssl.keystore.password=blablabla
ssl.truststore.password=blablabla

```

I didn't know what have i made wrong, can someone help me ? Have you ever been connected to a secured cluster using docker image and such files ?
