### ISSUE TITLE
kafdrop console is not coming up 

### ISSUE THREAD

**Issue by saicharana731** [obsidiandynamics/kafdrop#474]
Hi , kafdrop console is not coming up on localhost:9001 , I running it via docker-compose and from the desktop I see all the containers are running fine and no error in logs. but cannot access .

Would appreciate your support here . Im attaching the spec. filw
[New Text Document.txt](https://github.com/obsidiandynamics/kafdrop/files/10794214/New.Text.Document.txt)

**Comment by mehdihasan** [comment]
Hi @saicharana731, according to your docker compose, you have mapped Kafdrop container port 9000 to your host machine's port 9000. 

```
kafdrop:
    image: obsidiandynamics/kafdrop
    # restart: "no"
    ports:
      - "9000:9000"
```

You are suppose to access _Kafdrop console_ at **_localhost:9000_**, not localhost:9001.
