### ISSUE TITLE
I can't connect Broker when i run by Docker on Mac M1 

### ISSUE THREAD

**Issue by trinhcongduc** [obsidiandynamics/kafdrop#592]
⠿ Container kafka-kafdrop-kafka-1                                                                                                                        Recreated     0.0s
 ⠋ kafka The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                 

==================================.==============================

Kafka-kafdrop-kafdrop-1  | 2023-11-15 09:07:59.016  WARN 1 [| kafdrop-admin] o.a.k.c.NetworkClient                    : [AdminClient clientId=kafdrop-admin] Connection to node -1 (kafka/172.18.0.2:29092) could not be established. Broker may not be available.
<img width="1224" alt="Screenshot at Nov 15 16-15-48" src="https://github.com/obsidiandynamics/kafdrop/assets/38092290/0e4a9cb1-efb9-4a9d-b3d3-f7c081ddf849">

<img width="1222" alt="image" src="https://github.com/obsidiandynamics/kafdrop/assets/38092290/9f061691-e480-42d7-9d05-01c4a92156a4">

**Comment by ElAmen** [comment]
Hello,
I know it is been a year since this issue is closed but am currently experiencing it 

```yml
version: "2"
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss360K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
```


![image](https://github.com/user-attachments/assets/502ee60c-f164-4c6a-bf7c-7d35154158be)
